#%RAML 1.0
title: American Flights Api

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
  post:
    

  /{ID}:
    get:
      